---
- hosts: webservers
  become: yes
  tasks:
          - name: i want to install openjdk-8-jre in ansbile node
            apt:
                    name: openjdk-8-jre
                    state: present
